### ISSUE TITLE
Na matching distribution found for zensols.garmdown

### ISSUE THREAD

**Issue by pierretamisier** [garmin-data/garmdown#2]
I am on Ubuntu and try to install garmdown thru pip.

`pierre@pierre-thinkpad:~$ pip install zensols.garmdown
Collecting zensols.garmdown
Could not find a version that satisfies the requirement zensols.garmdown (from versions: )
No matching distribution found for zensols.garmdown`

Same issue with sudo.

**Comment by plandes** [comment]
This doesn't tell me much.  What version of python are you using?  Please also confirm your internet connection is good.

**Comment by pierretamisier** [comment]
Cheers Paul.
I actually was using the wrong version of python (2.7 vs 3).
Install is successful thru `pip3 install zensols.garmdown`
