### ISSUE TITLE
Extra activity_type mapping

### ISSUE THREAD

**Issue by nantasquad** [garmin-data/garmdown#3]
Garmin has added extra types, most of them are not mapped. When using my edge130 for tracking it creates an activity with 'road_biking' as type and the import doesn't know about this. To fix this I have to edit my activity type to change it to 'cycling' so the import works.

This can be resolved in a few ways, the easiest is to map multiple types to the same database option, and thus only using the parent type for reporting and storing. This does conflict with some of the current types, since at Garmin indoor_cycling is mapped to cycling as a parent and in garmdown it is its own type. I have kept the internal types. 

Based on their UI this is the list of all activity types that are available, including the parent. 
[garmin.json.txt](https://github.com/garmin-data/garmdown/files/4579852/garmin.json.txt)

I have mapped these to the current config in resources/fetch.conf and created a new config. There are still quite a lot activity types not mapped, since it is used in multiple places (database, google sheets, reporting) I didn't add new parent types.

The config below can be changed. This would resolve my issue. Can you implement these and publish a new version? That way I can update my current installation.

```
[activity_type]
bmx = c
cycling = c
cyclocross = c
downhill_biking = c
gravel_cycling = c
indoor_cycling = i
indoor_running = r
lap_swimming = l
mountain_biking = c
multi_sport = m
obstacle_run = r
open_water_swimming = o
recumbent_cycling = c
road_biking = c
running = r
street_running = r
strength_training = s
track_cycling = c
track_running = r
trail_running = r
treadmill_running = t
virtual_ride = c
virtual_run = r
```

**Comment by plandes** [comment]
Hi @nantasquad.  Thanks for finding this and updating the activity mappings.  This is [updated](https://github.com/garmin-data/garmdown/commit/24f54fe17d6570749536a13f8beef2d365b894ed) as a new release ([0.0.6](https://github.com/garmin-data/garmdown/releases/tag/v0.0.6)) and also now on pypi but it does have new requirements, which should be satisfied via pip.
